@startuml
!include style.puml
skinparam ArrowFontStyle plain

box "Logic" LOGIC_COLOR_T1
participant "c:ContactCommand" as ContactCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box "Model" MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "<<interface>>\nFilteredList<Person>" as FilteredList MODEL_COLOR
participant "<<class>>\nPerson" as Person MODEL_COLOR
end box

[-> ContactCommand : execute(m)
activate ContactCommand

ContactCommand -> Model : getFilteredPersonList()
activate Model
Model --> ContactCommand : lastShownList
deactivate Model

ContactCommand -> FilteredList : get(targetIndex)
activate FilteredList
FilteredList --> ContactCommand : personToMark
deactivate FilteredList
ContactCommand -[hidden]->
destroy FilteredList

ContactCommand -> Person : markAsContacted()
activate Person
Person --> ContactCommand : updatedPerson
deactivate Person

ContactCommand -> Model : setPerson(personToMark, updatedPerson)
activate Model
Model --> ContactCommand
deactivate Model

ContactCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
Model --> ContactCommand
deactivate Model

create CommandResult
ContactCommand -> CommandResult : new CommandResult(message)
activate CommandResult
CommandResult --> ContactCommand : r
deactivate CommandResult

[<-- ContactCommand : r
deactivate ContactCommand
ContactCommand -[hidden]->
destroy ContactCommand

@enduml
